### PR TITLE
make names and links for bundle charms

### PR DESCRIPTION
**Pull request by chillkang**
## Done
- make names and links for bundle charms
- remove links to charms that don't exist

## How to QA
- go to https://charmhub-io-1609.demos.haus/kubeflow and compare with this [design](https://app.zeplin.io/project/623c85b9b27d9fa62165f655/screen/62696009a63467bd2868b5ce)
- go to https://charmhub-io-1609.demos.haus/mlflow and check a link to `Mariadb K8S` is removed

## Issue / Card
Fixes https://warthogs.atlassian.net/browse/WD-4451

### CODE REVIEW

**Review by steverydz — CHANGES_REQUESTED** [review]
@chillkang The `Mariadb K8S` is still there, it just doesn't have an `href` attribute. If it needs to be there but shouldn't be a link then it's better to make it a `span`.

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by AnnSoMuller** [comment]
We should have the line under when hovering, as usual links

**Comment by AnnSoMuller** [comment]
nice!

**Pull request merged**
